name: Pull Request Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Pull Request Build
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup Git Config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm test
